version: "3.8"

services:
  nginx1:
    container_name: nginx1
    image: nginx:latest
    ports:
      - protocol: tcp
        published: 8080
        target: 80
  nginx2:
    container_name: nginx2
    image: nginx:latest
    ports:
      - "8081:80"
