version: "3.8"

services:
  mongodb1:
    container_name: mongodb1
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: febrianto
      MONGO_INITDB_ROOT_PASSWORD: febri123
      MONGO_INITDB_DATABASE: mhs
